# Generated by Django 3.1 on 2020-11-16 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing_FK',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniq_id', models.TextField(blank=True)),
                ('crawl_timestamp', models.DateTimeField(blank=True)),
                ('product_url', models.TextField(blank=True)),
                ('product_name', models.TextField(blank=True)),
                ('product_category_tree', models.TextField(blank=True)),
                ('pid', models.TextField(blank=True)),
                ('retail_price', models.TextField(blank=True)),
                ('discounted_price', models.TextField(blank=True)),
                ('image', models.TextField(blank=True)),
                ('is_FK_Advantage_product', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('product_rating', models.TextField(blank=True)),
                ('overall_rating', models.TextField(blank=True)),
                ('brand', models.TextField(blank=True)),
                ('product_specifications', models.TextField(blank=True)),
                ('list_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
